spring:
  profiles:
    active:
    - development
---

spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://mongodb/chitralimbu

---

spring:
  profiles: development
  data:
    mongodb:
      authentication-database: admin
      host: 192.168.0.157
      port: 27017
      database: ChitraLimbu
      username: chitra
      password: Cptgbdllmrh150!
      
---

logging:
  level:
    root: INFO
    
---

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
#        exclude: threaddump,heapdump
  endpoint:
    health:
      show-details: always

info:
  contact:
    email: chitralimbu@gmail.com
    phone: +447377547833