server:
  port: 6543
  ssl:
    key-store: 
    key-store-password:
    key-password:
---
spring:
  profiles:
    active:
    - development
---

spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://mongodb/chitralimbu

---

spring:
  profiles: development
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: ChitraLimbu
      username: chitra
      password: Cptgbdllmrh150!
      
---

spring:
  profiles: testing
  data:
    mongodb:
      uri: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/chitralimbu

---

logging:
    level:
      root: INFO
    
---

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
#        exclude: threaddump,heapdump
  endpoint:
    health:
      show-details: always

info:
  contact:
    email: chitralimbu@gmail.com
    phone: +447377547833